### PR TITLE
proposal: Add astx to the makim proposal

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by xmnlab** [comment]
@apkrelling @abhijeetSaroha @investor-uyah 

when you have time could you review this proposal please?

@EverVino do you want to act as project manager in this project?

**Comment by xmnlab** [comment]
just this file is important for this review: https://github.com/OpenScienceLabs/grant-proposals/pull/15/files#diff-6169f44d43179b521a323aad64d5ec4cd59505c3ed8cd461896a51a31a2dd62cR1

the other changes are basically changes in the folder's organization

**Comment by abhijeetSaroha** [comment]
@xmnlab , I've reviewed the proposal, and everything looks good to me!

**Comment by apkrelling** [comment]
LGTM as well :slightly_smiling_face:

**Comment by investor-uyah** [comment]
Hello Ivan. It looks good as far as I can tell.

**Comment by xmnlab** [comment]
thanks @abhijeetSaroha @apkrelling @investor-uyah  for the review, appreciate that.

**Comment by EverVino** [comment]
Hello @xmnlab , thanks for the offer, but these months I'm going to be tight on my schedule, I won't be able to this time.

**Comment by xmnlab** [comment]
@EverVino, thanks for the response!

**Pull request merged**
